// Tastenkürzel + Persistenz nach Neuladen (echte Uhr, kein Testmodus)
import { chromium } from 'playwright';
const BASE = process.env.BASE || 'http://localhost:5173/';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 1920, height: 1080 } });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
const st = () => p.evaluate(() => { const h = window.__hackday; const L = h.L; const help = [...document.querySelectorAll('#stage > div')].find((d) => d.textContent.startsWith('TASTENKÜRZEL')); const t = (ms) => new Date(ms).toTimeString().slice(0,5);
  return { idx: L.idx, ende: L.ende, state: L.state, end: L.ende ? '-' : t(L.slots[L.idx].end), rem: Math.round(L.remaining/1000), blinds: L.blinds, paused: L.paused, weather: h.weather.current, ops: h.ops.length, anim: h.current, printer: h.printer.state + '/' + h.printer.obj, idle: h.idleOn, help: !!help && help.style.display !== 'none', toast: [...document.querySelectorAll('#stage > div')].filter((d) => d.style.top === '978px')[0]?.textContent }; });
const key = async (k, label) => { await p.keyboard.press(k); await p.waitForTimeout(250); const s = await st(); console.log(label.padEnd(22), JSON.stringify(s)); return s; };
const ready = async () => { await p.waitForSelector('body[data-ready="1"]', { state: 'attached' }); await p.waitForTimeout(300); };
await p.goto(BASE); await ready();
await p.evaluate(() => localStorage.clear()); await p.reload(); await ready();
console.log('Start'.padEnd(22), JSON.stringify(await st()));
await key('+', '+ (5 min länger)');
await key('-', '- (5 min kürzer)');
await key('+', '+');
await key('p', 'P Pause');
await p.waitForTimeout(2000);
const s1 = await st(); console.log('2 s später (Pause)'.padEnd(22), 'Rest', s1.rem);
await key('p', 'P weiter');
await key('j', 'J Jalousie');
await key('w', 'W Wetter');
await key('w', 'W Wetter');
const beforeReload = await key('ArrowLeft', '← zurück');
await p.reload(); await ready();
const after = await st(); console.log('nach Neuladen'.padEnd(22), JSON.stringify(after));
console.log('Persistenz ok:', after.idx === beforeReload.idx && after.end === beforeReload.end && after.ops === beforeReload.ops);
await key('ArrowRight', '→ nächste');
await key('r', 'R (1×)');
await key('r', 'R (2×) Reset');
await key('f', 'F Vollbild');
// ---- neue Tasten ----
await key('Shift+?', '? Hilfe auf');
await key('Escape', 'Esc Hilfe zu');
await key('l', 'L Leerlauf aus');
await p.reload(); await ready();
console.log('L nach Neuladen'.padEnd(22), JSON.stringify(await st()));
await key('l', 'L Leerlauf an');
await key('h', 'H Winken');
await key('k', 'K Kaffee (läuft noch was)');
await p.waitForTimeout(4000);
console.log('4 s später'.padEnd(22), JSON.stringify(await st()));
await p.waitForFunction(() => !window.__hackday.busy, null, { timeout: 30000 });
console.log('Queue leer'.padEnd(22), JSON.stringify(await st()));
await key('d', 'D (printing → fertig)');
await key('d', 'D (done → abholen)');
await p.waitForFunction(() => !window.__hackday.busy && window.__hackday.printer.state === 'empty', null, { timeout: 30000 });
console.log('nach Abholen'.padEnd(22), JSON.stringify(await st()));
await key('d', 'D (empty → starten)');
await p.waitForFunction(() => !window.__hackday.busy && window.__hackday.printer.state === 'printing', null, { timeout: 30000 });
console.log('nach Start'.padEnd(22), JSON.stringify(await st()));
console.log('Fehler:', errs.length ? errs : 'keine');
await b.close();
